# Generated by Django 5.1.15 on 2026-09-26 10:16

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=4,
                        verbose_name="Коэффициент рейтинга",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "уровень соревнования",
                "verbose_name_plural": "уровни соревнований",
                "ordering": ["order", "-coefficient"],
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Например: ALG, PROD, CTF",
                        max_length=16,
                        verbose_name="Короткий код",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "дисциплина",
                "verbose_name_plural": "дисциплины",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("regulation", "Положения"),
                            ("rules", "Правила"),
                            ("official", "Официальные документы"),
                            ("material", "Полезные материалы"),
                        ],
                        default="regulation",
                        max_length=20,
                        verbose_name="Раздел",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается простая разметка: ## заголовок, - список, **жирный**, `код`.",
                        verbose_name="Текст документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=core.models.material_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "документы и материалы",
                "ordering": ["category", "order", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "category",
                    models.CharField(
                        default="Общее", max_length=60, verbose_name="Категория"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
            ],
            options={
                "verbose_name": "вопрос FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["category", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Название"
                    ),
                ),
                ("short", models.CharField(max_length=16, verbose_name="Сокращение")),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Бонус к рейтингу"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок (от высшего)"
                    ),
                ),
            ],
            options={
                "verbose_name": "разряд / звание",
                "verbose_name_plural": "разряды и звания",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "excerpt",
                    models.CharField(blank=True, max_length=300, verbose_name="Анонс"),
                ),
                ("body", models.TextField(verbose_name="Текст")),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        default="Новости",
                        max_length=40,
                        verbose_name="Рубрика",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Закрепить"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликована"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "новости",
                "ordering": ["-is_pinned", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("kind", models.CharField(default="info", max_length=20)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
