# Generated by Django 5.1.15 on 2026-09-26 10:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("athlete", "Спортсмен"),
                            ("organizer", "Организатор"),
                        ],
                        db_index=True,
                        default="athlete",
                        max_length=16,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Отчество"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Город"),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Учебное заведение / организация",
                    ),
                ),
                (
                    "qualification_verified",
                    models.BooleanField(
                        default=False, verbose_name="Разряд подтверждён"
                    ),
                ),
                (
                    "bio",
                    models.CharField(blank=True, max_length=500, verbose_name="О себе"),
                ),
                (
                    "is_profile_public",
                    models.BooleanField(default=True, verbose_name="Публичный профиль"),
                ),
                (
                    "show_institution",
                    models.BooleanField(
                        default=True, verbose_name="Показывать учебное заведение"
                    ),
                ),
                (
                    "consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Согласие на обработку ПД"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(db_index=True, default=0, verbose_name="Рейтинг"),
                ),
                (
                    "rating_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место в рейтинге"
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
