# Generated by Django 5.1.15 on 2026-09-26 10:16

import competitions.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="Краткое описание"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Подробное описание"),
                ),
                (
                    "rules",
                    models.TextField(
                        blank=True, verbose_name="Правила и инструкция для участников"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн"),
                            ("offline", "Очно"),
                            ("hybrid", "Смешанный"),
                        ],
                        default="online",
                        max_length=10,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="Онлайн, платформа ФСП Контест",
                        max_length=200,
                        verbose_name="Место проведения",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(db_index=True, verbose_name="Начало"),
                ),
                (
                    "end_at",
                    models.DateTimeField(db_index=True, verbose_name="Окончание"),
                ),
                (
                    "registration_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало регистрации"
                    ),
                ),
                (
                    "registration_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Если не указано — регистрация открыта до окончания соревнования",
                        null=True,
                        verbose_name="Окончание регистрации",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Лимит участников"
                    ),
                ),
                (
                    "has_contest",
                    models.BooleanField(
                        default=True,
                        help_text="Задания и отправка решений на платформе. Выключите для очных/внешних соревнований — результаты вносятся вручную.",
                        verbose_name="Контест на платформе",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Попыток на задачу",
                    ),
                ),
                (
                    "show_live_standings",
                    models.BooleanField(
                        default=True,
                        verbose_name="Показывать предварительную таблицу во время тура",
                    ),
                ),
                (
                    "external_platform",
                    models.CharField(
                        blank=True,
                        help_text="Например: Codeforces",
                        max_length=80,
                        verbose_name="Внешняя платформа",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на внешнее соревнование"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Опубликован"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "results_published",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Итоги подведены"
                    ),
                ),
                (
                    "results_published_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.discipline",
                        verbose_name="Дисциплина",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.competitionlevel",
                        verbose_name="Уровень",
                    ),
                ),
            ],
            options={
                "verbose_name": "соревнование",
                "verbose_name_plural": "соревнования",
                "ordering": ["-start_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "letter",
                    models.CharField(
                        editable=False, max_length=3, verbose_name="Индекс"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "statement",
                    models.TextField(
                        help_text="Разметка: ## заголовок, - список, **жирный**, `код`, ``` блок кода ```",
                        verbose_name="Условие",
                    ),
                ),
                (
                    "input_spec",
                    models.TextField(blank=True, verbose_name="Формат входных данных"),
                ),
                (
                    "output_spec",
                    models.TextField(blank=True, verbose_name="Формат выходных данных"),
                ),
                (
                    "sample_input",
                    models.TextField(blank=True, verbose_name="Пример ввода"),
                ),
                (
                    "sample_output",
                    models.TextField(blank=True, verbose_name="Пример вывода"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "limits",
                    models.CharField(
                        blank=True,
                        default="1 с · 256 МБ",
                        max_length=80,
                        verbose_name="Ограничения",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Максимальный балл",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to=competitions.models.task_upload_to,
                        verbose_name="Файл-материал",
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(blank=True, editable=False, max_length=200),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Ссылка на материалы"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "задание",
                "verbose_name_plural": "задания",
                "ordering": ["order", "id"],
                "unique_together": {("competition", "letter")},
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python 3"),
                            ("cpp", "C++ 17"),
                            ("c", "C"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("kotlin", "Kotlin"),
                            ("go", "Go"),
                            ("js", "JavaScript"),
                            ("pascal", "Pascal"),
                            ("other", "Другой / текстовый ответ"),
                        ],
                        default="python",
                        max_length=16,
                        verbose_name="Язык",
                    ),
                ),
                ("code", models.TextField(blank=True, verbose_name="Код решения")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=competitions.models.submission_upload_to,
                        verbose_name="Файл решения",
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "На проверке"), ("reviewed", "Проверено")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Баллы"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий проверяющего"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="competitions.competition",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="competitions.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "решение",
                "verbose_name_plural": "решения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
                "ordering": ["created_at"],
                "unique_together": {("competition", "athlete")},
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.PositiveIntegerField(verbose_name="Место")),
                ("score", models.FloatField(default=0, verbose_name="Баллы")),
                (
                    "penalty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Штрафное время, мин"
                    ),
                ),
                (
                    "solved",
                    models.PositiveIntegerField(default=0, verbose_name="Решено задач"),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("participants_total", models.PositiveIntegerField(default=0)),
                (
                    "rating_points",
                    models.FloatField(default=0, verbose_name="Рейтинговые очки"),
                ),
                ("is_manual", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "результат",
                "verbose_name_plural": "результаты",
                "ordering": ["competition", "place"],
                "unique_together": {("competition", "athlete")},
            },
        ),
    ]
